x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

services:
  api:
    <<: *default-logging
    build: ./rag
    ports:
      - "8000:8000"
    env_file: envs/.env.rag
    volumes:
      - ./rag/src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      parser:
        condition: service_healthy

  parser:
    <<: *default-logging
    build: ./parser
    ports:
      - "8001:8000"
    env_file: envs/.env.parser
    volumes:
      - ./parser/src:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/schema/openapi.json"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  qdrant:
    <<: *default-logging
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./.volumes/qdrant:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/6333'"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    <<: *default-logging
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: envs/.env.postgres
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leetcode -d leetcode"]
      interval: 5s
      timeout: 3s
      retries: 5
